import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = async (file: File) => {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
    reader.readAsDataURL(file);
  });
  return {
    inlineData: { data: await base64EncodedDataPromise, mimeType: file.type },
  };
};

export const generateBannerImage = async (
  title: string,
  price: number,
  images: File[]
): Promise<string> => {
  try {
    const imageParts = await Promise.all(images.map(fileToGenerativePart));
    
    const textPart = {
        text: `Create an attractive, high-quality promotional banner for a food item. The banner should feature the dishes from the provided images.
        The banner must prominently include the title "${title}" and the price "S/${price.toFixed(2)}".
        Combine the images into a single, visually appealing 600x600 square composition with a beautiful, cohesive background suitable for a premium restaurant.
        The overall style should be vibrant, professional, and appetizing. Ensure the text is clear and easy to read.`
    };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [textPart, ...imageParts],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });
    
    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            const base64ImageBytes: string = part.inlineData.data;
            return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
        }
    }

    throw new Error("No image was generated by the AI.");

  } catch (error) {
    console.error("Error generating banner with Gemini:", error);
    throw new Error("Failed to generate AI banner. Please try again.");
  }
};